server:
  port: 0
  servlet:
    encoding:
      charset: UTF-8
      enable: true
      force: true
  shutdown: graceful

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER}:8888
  profiles:
    active: ${PROFILE}
  cloud:
    config:
      fail-fast: true # true: config 서버에 연결하지 못하면 앱이 실행되지 않도록 함
    bus:
      enabled: true
      refresh:
        enabled: true
      destination: config-topic
  kafka:
    bootstrap-servers: http://${KAFKA_SERVER}:9092 # 카프카 클러스터 주소
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_SERVER}:3306/user?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${NOCTEM_DB_USERNAME}
    password: ${NOCTEM_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka

management:
  endpoints:
    web:
      base-path: /api/user-service/actuator
      exposure:
        include: health, refresh, httptrace, busrefresh, prometheus, metrics
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

global:
  jwt-token:
    signer: ${NOCTEM_JWT_SIGNER}
  value: local-user